name: Acceptance Tests Code Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  python-tests:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python "3.12"
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pipenv setuptools wheel
          pipenv install --dev --deploy

      - name: Run Checks
        run: |
          make flake
          make vulture
          make build