package uk.gov.ons.ssdc.common.model.entity;

public enum EventType {
  NEW_CASE,
  RECEIPT,
  REFUSAL,
  ERASE_DATA,
  EQ_LAUNCH,
  INVALID_CASE,
  UAC_AUTHENTICATION,
  TELEPHONE_CAPTURE,
  PRINT_FULFILMENT,
  EXPORT_FILE,
  DEACTIVATE_UAC,
  UPDATE_SAMPLE,
  UPDATE_SAMPLE_SENSITIVE,
  SMS_FULFILMENT,
  ACTION_RULE_SMS_REQUEST,
  EMAIL_FULFILMENT,
  ACTION_RULE_EMAIL_REQUEST,
  ACTION_RULE_SMS_CONFIRMATION,
  ACTION_RULE_EMAIL_CONFIRMATION
}
