package uk.gov.ons.ssdc.common.model.entity;

public enum JobStatus {
  FILE_UPLOADED,
  STAGING_IN_PROGRESS,
  VALIDATION_IN_PROGRESS,
  VALIDATED_OK,
  VALIDATED_WITH_ERRORS,
  VALIDATED_TOTAL_FAILURE,
  PROCESSING_IN_PROGRESS,
  PROCESSED,
  CANCELLED
}
