DO $$
BEGIN
    CREATE ROLE rm_superuser;
    EXCEPTION WHEN duplicate_object THEN RAISE NOTICE '%, re-applying role grants and privileges', SQLERRM USING ERRCODE = SQLSTATE;
END
$$;

GRANT CONNECT ON DATABASE rm TO rm_superuser;

GRANT USAGE ON SCHEMA casev3 TO rm_superuser;
GRANT USAGE ON SCHEMA uacqid TO rm_superuser;
GRANT USAGE ON SCHEMA exceptionmanager TO rm_superuser;
GRANT USAGE ON SCHEMA ddl_version TO rm_superuser;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA casev3 TO rm_superuser;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA casev3 TO rm_superuser;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA uacqid TO rm_superuser;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA uacqid TO rm_superuser;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA exceptionmanager TO rm_superuser;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA exceptionmanager TO rm_superuser;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA ddl_version TO rm_superuser;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA ddl_version TO rm_superuser;
GRANT ALL PRIVILEGES ON DATABASE rm TO rm_superuser;

ALTER DEFAULT PRIVILEGES IN SCHEMA casev3 GRANT ALL PRIVILEGES ON TABLES TO rm_superuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA uacqid GRANT ALL PRIVILEGES ON TABLES TO rm_superuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA exceptionmanager GRANT ALL PRIVILEGES ON TABLES TO rm_superuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA ddl_version GRANT ALL PRIVILEGES ON TABLES TO rm_superuser;
